name: Java CI with Gradle
on: 
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:
    branches: [ 'main' ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: gradlew execute permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
