name: Java CI with Gradle
on: 
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch: 
    branches: [ 'main' ]
    
jobs:
  build:
    name: Java 11 build on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]     
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Allow execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build 
