name: Java CI with Gradle
on: 
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:
    
jobs:
  build:
    name: Java 11 build on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Allow execute permissions for gradlew
        run: chmod +x gradlew
        
      - name: Execute Gradle build
        run: ./gradlew build
